# Ansible playbook to install Magento on a server.
# Change hosts.yml to your server IP.
# Run with: ansible-playbook -i hosts.yml magento.yml -k -vvv
# Created by Eric Cavalcanti - eric.cavalcanti@rackspace.com

---
- name: Install magento, MySQL, httpd, PHP and Varnish
  hosts: magento-server
  user: root

  roles:
    - common
    - { role: mysql, when: db_choice == 'mysql' }
    - { role: percona, when: db_choice == 'percona' }
    - httpd
    - php
    - { role: varnish, when: varnish_install == 'install' }
    - { role: magento, when: magento_install == 'install' }
