# Ansible playbook to install Magento on a server.
# Change hosts.yml to your server IP.
# Make sure you change to your private-key used on AWS to connect to the ec2.
# Run with: ansible-playbook -i hosts.yml magento.yml -k -vvv --private-key ~/.ssh/id_rsa --become
# Created by Eric Cavalcanti - ecavalcanti.it@gmail.com

---
- name: Install magento, MySQL, httpd, PHP and Varnish
  hosts: magento-server
  user: ec2-user

  roles:
    - common
    - { role: mysql, when: db_choice == 'mysql' }
    - { role: percona, when: db_choice == 'percona' }
    - httpd
    - php
    - { role: varnish, when: varnish_install == 'install' }
    - { role: magento, when: magento_install == 'install' }
